#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


# rodar os testes
./vendor/bin/sail artisan test --parallel
if [ $? -ne 0 ]; then
    echo "Houve falha nos testes. Arrume antes de continuar... 😉";
    exit 1;
fi;

# Formatar cada arquivo alterado usando o Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
        echo "passou aqui - ${FILE}"
    ./vendor/bin/sail bin pint "${FILE}" > /dev/null >&1;

    git add "${FILE}";

done;

exit 0;
